### ISSUE TITLE
Not finding fonts folder

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/fontloader-plugin#3]
Using this on Windows and I have a "fonts" folder but there's a NPE in `getFontsFolder()`...

**Comment by Phillipus** [comment]
Yes, it expects to see a "fonts" folder in the plugin. By default that does not exist. This is the plug-in without fonts shipped.

**Comment by Phillipus** [comment]
@jbsarrodie I've pushed a fix if you'd like to test it.

**Comment by Phillipus** [comment]
Because the "fonts" folder is empty it doesn't get installed when Archi installs the plugin. This fix will ignore that.

**Comment by jbsarrodie** [comment]
Thank you. I guess I did test but not on a clean Archi setup.
